### ISSUE TITLE
state を更新する処理がうまく動いていない

### ISSUE THREAD

**Issue by 7kaji** [7kaji/react-ts-app#4]
![image](https://user-images.githubusercontent.com/1157309/80919286-1e41c080-8da4-11ea-9fb6-e5431668242d.png)

- ` - ` button (done) と `delete` button を押すと、対象の reducer が 2回呼ばれてしまっているのが原因っぽい
-  `delete` button は (2回呼ばれても問題ないから)一応動いている

**Comment by TsuyoshiNumano** [comment]
2回呼ばれている原因はこれですね。
https://stackoverflow.com/questions/55055793/react-usereducer-hook-fires-twice-how-to-pass-props-to-reducer

ざっくりいうと、useReducer がレンダリングするコンポーネント内で呼ばれているためです。

流れとしては

1. Action を実行すると
2. Reducer が呼ばれる
3. Reducer が呼ばれるとステートが更新される
4. ステートが更新されたので App がレンダリングされる
5. レンダリングに伴って App.tsx で定義している Reducer がまた呼ばれる
6. ステートが更新される


7で5(レンダリングに伴って App.tsx で定義している Reducer がまた呼ばれる)が起こって無限ループしそうですが、更新が早すぎると無限ループしないようですね。（自分もここがよくわかっていないですが。。。）



解決策は

A: stackoverflow に書いてあるように、useReducer の関数を useCallback で memo 化して、明示的に、ステートの変更がない限り、再レンダリングをされないようにする
B: レンダリング関数内に Provider を置かない。


Bの方が簡単だと思うので、サンプルコードをいかに置いておきますね。

1. App.tsx のContext を利用している記述を切り出して `TodoContextProvider` を作る

```jsx
import React, { useReducer } from 'react';
import {
  todoReducer,
  INITIAL_STATE,
  TodoStateContext,
} from 'contexts/todoStore';

const TodoContextProvider: React.FC = ({ children }) => {
  const [state, dispatch] = useReducer(todoReducer, INITIAL_STATE);
  return (
    <TodoStateContext.Provider value={{ state, dispatch }}>
      {children}
    </TodoStateContext.Provider>
  );
};

export default TodoContextProvider;
```


2. アプリのルートである `index.ts` で上記を読み込む

```js
import TodoContextProvider from 'TodoContextProvider';

ReactDOM.render(
  <TodoContextProvider>
    <React.StrictMode>
      <App />
    </React.StrictMode>
  </TodoContextProvider>,
  document.getElementById('root'),
);
```

`<React.StrictMode>`  を Wrap する感じで呼んでください。
これで、ステートの更新ごとのレンダリングからは切り離されることができるので、１回しか呼ばれないようになり done がうまく動くと思います。
（別に１で切り出さなくても、2 の `index.ts` の中に書いても多分動くと思います（試してないのでわかりませんが。） ）

![context_provider](https://user-images.githubusercontent.com/11643610/80933611-76f27700-8dff-11ea-9681-884ccf7c6d47.gif)

**Comment by 7kaji** [comment]
https://github.com/7kaji/react-ts-app/pull/5

無事うごきました！！
ありがとうござます 🙏
